name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1

      - name: Install dependencies
        run: go mod tidy # Now, it should work with Go >= 1.11

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
